### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by Yuiix** [Industrial-Shields/rpiplc-python3-lib#3]
not sure if is an issue with the new OS of rasp but the library is not complete to actually use it, it does not generate the .so

ibrpiplc.so: cannot open shared object file: No such file or directory

**Comment by jordicasals** [comment]
Hi @Yuiix,

try to install the [rpiplc-lib](https://github.com/Industrial-Shields/rpiplc-lib) library before using the rpiplc-python3-lib. You may have it already installed with the Industrial Shields RPIPLC image, but in case you use a RaspberryPI original image, you need to install it.

Best regards,

**Comment by Yuiix** [comment]
im refering to the python library, im not sure but is not that the C/C++ lib?

**Comment by Yuiix** [comment]
seems like even so after install the rpiplc-lib the error persist and makes it look like there no module named 'rpiplc_lib'
